/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.infinull.sit;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppReturnsUsage() {
//        Tests Go Here
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", App.main());
    }
}
